version: 0.2

phases:
    install:
      runtime-versions:
        java: corretto11
      commands:
        - echo no commands yet
    pre_build:
      commands:
        - echo no commands here
    build:
      commands:
        - echo Build started on `date`
        - cd codepipeline && mvn clean install
    post_build:
      commands:
        - echo no commands here
artifacts:
  files:
    - 'codepipeline/target/codepipeline.jar'
    - 'appspec.yml'
    - 'scripts/before_install.sh'
    - 'scripts/after_install.sh'
    - 'scripts/start_server.sh'
    - 'scripts/stop_server.sh'